test_format = 1.0

[default]

    args.upload = true
    args.public_library = true

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.b8f9f95.name = "0.6.19~ynh8"
