#!/bin/bash

# Source YunoHost helpers
source /usr/share/yunohost/helpers

#pour récupérer l'app_id, on prend le nom du fichier puis on retire les 3 premiers caratères
app=`basename "$0"`
app=${app:3}
source /etc/yunohost/apps/$app/scripts/_common.sh


username=$1
mail=$2
pass_clear=$3
final_path=$(ynh_app_setting_get $app final_path)

public_library=$(ynh_app_setting_get "$app" public_library)
#User are duplicated in the database only if library is public
if [ $public_library -eq 1 ]; then 
	######################################
	#1 get admin user and id from database
	######################################
	#we take the admin user as we're sure there is at least this one
	
	admin=$(ynh_app_setting_get $app admin)
	admin_id=$(sqlite3 $final_path/app.db "SELECT id FROM user WHERE nickname='$admin'")
	
	######################################
	#get user table structure
	######################################
	table_schema=$(get_db "user")
	
	######################################
	#Build new entry for user
	######################################
	insert_user=$table_schema
	insert_user="${insert_user/id/null}" #so that a new entry is created
	insert_user="${insert_user/nickname/\'$username\'}"
	insert_user="${insert_user/role/0}" #standard role
	pass_hash=$(python /etc/yunohost/apps/$app/conf/generate_password_hash.py "$pass_clear" $final_path/vendor)
	insert_user="${insert_user/password/\'$pass_hash\'}" #we get the same pass even if it's not thanks to LDAP, ones never knows...
	insert_user="${insert_user/email/\'$mail\'}"
	
	#######################################
	# Insert New entry in database
	#######################################
	
	sqlite3 $final_path/app.db "INSERT INTO user ($table_schema) SELECT $insert_user FROM user WHERE ID = $admin_id;"
fi