#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#Get settings from database in case it has been changed in the app
calibre_dir=$(sqlite3 $install_dir/app.db "SELECT config_calibre_dir FROM settings WHERE ID=1")
#Save it in settings so that it can be used back afterward
calibre_dir=${calibre_dir%/}
ynh_app_setting_set --key="calibre_dir" --value="$calibre_dir"

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

#This will backup the app.db file at the same time
ynh_backup "$install_dir"

#=================================================
# BACKUP THE KEPUBIFY BINARY
#=================================================

ynh_backup "/opt/kepubify/$app"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP LOGROTATE
#=================================================

ynh_backup "/etc/logrotate.d/$app"


#=================================================
# BACKUP FAIL2BAN CONFIGURATION
#=================================================

ynh_backup "/etc/fail2ban/jail.d/$app.conf"
ynh_backup "/etc/fail2ban/filter.d/$app.conf"

#=================================================
# BACKUP SYSTEMD
#=================================================

ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# BACKUP THE DATA DIRECTORY
#=================================================

ynh_backup "$calibre_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
