#!/bin/bash

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================
ynh_script_progression "Backing up the app before changing its url (may take a while)..."

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

#
if [ $new_path = "/" ] ; then
	ynh_replace --match="        proxy_set_header	X-Script-Name		__PATH__;"
	            --replace="        proxy_set_header	X-Script-Name		/__PATH__;"
	            --file=../conf/nginx.conf
else
	ynh_replace --match="        proxy_set_header	X-Script-Name		/__PATH__;"
	            --replace="        proxy_set_header	X-Script-Name		__PATH__;"
	            --file="../conf/nginx.conf"
fi

if $(ynh_permission_has_user --permission=main --user=visitors); then
	ynh_replace --match="        proxy_set_header	X-Remote-User" \
	            --replace="#       proxy_set_header	X-Remote-User" \
	            --file="../conf/nginx.conf"
else
	ynh_replace --match="#       proxy_set_header	X-Remote-User" \
	            --replace="        proxy_set_header	X-Remote-User" \
	            --file="../conf/nginx.conf"
fi

ynh_config_change_url_nginx

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --wait_until="Starting Gevent server on" -t 30

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
