#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove the service from the list of services known by Yunohost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing the systemd service..."

ynh_config_remove_systemd


#=================================================
# REMOVE DATA DIR
#=================================================

# Remove the data directory if --purge option is used
if [ "${YNH_APP_PURGE:-0}" -eq 1 ]
then
	ynh_script_progression "Removing app data directory..."
	ynh_safe_rm "$calibre_dir"
fi

#=================================================
# REMOVE KEPUBIFY DIR
#=================================================
ynh_script_progression "Removing kepubify directory..."

ynh_safe_rm "/opt/kepubify/$app"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx web server configuration..."

ynh_config_remove_nginx

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Removing logrotate configuration..."

ynh_config_remove_logrotate

#=================================================
# REMOVE FAIL2BAN CONFIGURATION
#=================================================
ynh_script_progression "Removing Fail2Ban configuration..."

ynh_config_remove_fail2ban

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- $port$"
then
	ynh_script_progression "Closing port $port..."
	yunohost firewall disallow TCP $port 2>&1
fi

#Restore Imagick policy
if [ -z /etc/ImageMagick-6/policy.xml ]; then
	ynh_replace --match="<policy domain="coder" rights="read" pattern="PDF" />" \
                --replace="<policy domain="coder" rights="none" pattern="PDF" />" \
                --target="/etc/ImageMagick-6/policy.xml"
fi

ynh_script_progression "Removing log file..."

ynh_safe_rm "$log_file"
ynh_safe_rm "$access_log_file"

#=================================================
# MESSAGE TO USER
#=================================================
ynh_script_progression "Removal of $app completed"

# Remove the data directory if --purge option is used
if [ "${YNH_APP_PURGE:-0}" -eq 0 ]
then
	ynh_print_info "The library folder $calibre_dir was not deleted. Delete it manually if required"
fi
